pipeline {
    agent any

    environment {
        AWS_REGION = 'us-east-1'
        AWS_ACCOUNT_ID = '141216419469'
        AWS_CRED_ID = 'aws-credentials-id'  // Jenkins credentials ID for AWS
        ECR_REPOSITORY = 'logist'
        IMAGE_TAG = 'latest'
        CONTAINER_NAME = 'logist6'
        CONTAINER_PORT = '80'
        HOST_PORT = '8087'
    }

    stages {
        stage('Login to ECR') {
            steps {
                script {
                    withAWS(credentials: "${141216419469}", region: "${us-east-1}") {
                        sh """
                        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 141216419469.dkr.ecr.us-east-1.amazonaws.com
                        """
                    }
                }
            }
        }

        stage('Pull Docker Image') {
            steps {
                script {
                    sh "docker pull ${141216419469}.dkr.ecr.${us-east-1}.amazonaws.com/${logist}:${latest}"
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                script {
                    sh """
                    docker run -d --name ${logist6} -p ${8087}:${80} ${141216419469}.dkr.ecr.${us-east-1}.amazonaws.com/${logist}:${latest}
                    """
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
