pipeline{
   agent any 
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage('sonar-scan'){
        steps{
            withSonarQubeEnv('sonarqube'){
        sh ('mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=EnockEssel_geo-app')
            }
        }
    }
    stage("maven"){
        steps{ 
        sh 'mvn clean validate compile install test package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uAdmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
            <PATH_TO_FILE> "http://ec2-52-204-60-206.compute-1.amazonaws.com:8081/artifactory/geolocation/<TARGET_FILE_PATH>"'
        }
    }
   }
}
 